development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://xlskuzqezrfwcy:10071462ee4f6242384f29fe641500c56f32dc338941c7f9ef3b5eb6398694c0@ec2-23-21-229-48.compute-1.amazonaws.com:5432/dahjenuv5dlv00
  channel_prefix: Blog_production
